#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_WEB_GYM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WiBuGym")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangKyKhoaTap(DangKyKhoaTap instance);
    partial void UpdateDangKyKhoaTap(DangKyKhoaTap instance);
    partial void DeleteDangKyKhoaTap(DangKyKhoaTap instance);
    partial void InsertCLB(CLB instance);
    partial void UpdateCLB(CLB instance);
    partial void DeleteCLB(CLB instance);
    partial void InsertKhoaTap(KhoaTap instance);
    partial void UpdateKhoaTap(KhoaTap instance);
    partial void DeleteKhoaTap(KhoaTap instance);
    partial void InsertLoaiTinTuc(LoaiTinTuc instance);
    partial void UpdateLoaiTinTuc(LoaiTinTuc instance);
    partial void DeleteLoaiTinTuc(LoaiTinTuc instance);
    partial void InsertPT(PT instance);
    partial void UpdatePT(PT instance);
    partial void DeletePT(PT instance);
    partial void InsertTaiKhoanKH(TaiKhoanKH instance);
    partial void UpdateTaiKhoanKH(TaiKhoanKH instance);
    partial void DeleteTaiKhoanKH(TaiKhoanKH instance);
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WiBuGymConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangKyKhoaTap> DangKyKhoaTaps
		{
			get
			{
				return this.GetTable<DangKyKhoaTap>();
			}
		}
		
		public System.Data.Linq.Table<CLB> CLBs
		{
			get
			{
				return this.GetTable<CLB>();
			}
		}
		
		public System.Data.Linq.Table<KhoaTap> KhoaTaps
		{
			get
			{
				return this.GetTable<KhoaTap>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTinTuc> LoaiTinTucs
		{
			get
			{
				return this.GetTable<LoaiTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<PT> PTs
		{
			get
			{
				return this.GetTable<PT>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanKH> TaiKhoanKHs
		{
			get
			{
				return this.GetTable<TaiKhoanKH>();
			}
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanQTV> TaiKhoanQTVs
		{
			get
			{
				return this.GetTable<TaiKhoanQTV>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyKhoaTap")]
	public partial class DangKyKhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGuest;
		
		private int _idCourse;
		
		private EntityRef<KhoaTap> _KhoaTap;
		
		private EntityRef<TaiKhoanKH> _TaiKhoanKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGuestChanging(int value);
    partial void OnidGuestChanged();
    partial void OnidCourseChanging(int value);
    partial void OnidCourseChanged();
    #endregion
		
		public DangKyKhoaTap()
		{
			this._KhoaTap = default(EntityRef<KhoaTap>);
			this._TaiKhoanKH = default(EntityRef<TaiKhoanKH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuest", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idGuest
		{
			get
			{
				return this._idGuest;
			}
			set
			{
				if ((this._idGuest != value))
				{
					if (this._TaiKhoanKH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidGuestChanging(value);
					this.SendPropertyChanging();
					this._idGuest = value;
					this.SendPropertyChanged("idGuest");
					this.OnidGuestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCourse", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCourse
		{
			get
			{
				return this._idCourse;
			}
			set
			{
				if ((this._idCourse != value))
				{
					if (this._KhoaTap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCourseChanging(value);
					this.SendPropertyChanging();
					this._idCourse = value;
					this.SendPropertyChanged("idCourse");
					this.OnidCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaTap_DangKyKhoaTap", Storage="_KhoaTap", ThisKey="idCourse", OtherKey="idCourse", IsForeignKey=true)]
		public KhoaTap KhoaTap
		{
			get
			{
				return this._KhoaTap.Entity;
			}
			set
			{
				KhoaTap previousValue = this._KhoaTap.Entity;
				if (((previousValue != value) 
							|| (this._KhoaTap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaTap.Entity = null;
						previousValue.DangKyKhoaTaps.Remove(this);
					}
					this._KhoaTap.Entity = value;
					if ((value != null))
					{
						value.DangKyKhoaTaps.Add(this);
						this._idCourse = value.idCourse;
					}
					else
					{
						this._idCourse = default(int);
					}
					this.SendPropertyChanged("KhoaTap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKH_DangKyKhoaTap", Storage="_TaiKhoanKH", ThisKey="idGuest", OtherKey="idGuest", IsForeignKey=true)]
		public TaiKhoanKH TaiKhoanKH
		{
			get
			{
				return this._TaiKhoanKH.Entity;
			}
			set
			{
				TaiKhoanKH previousValue = this._TaiKhoanKH.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoanKH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoanKH.Entity = null;
						previousValue.DangKyKhoaTaps.Remove(this);
					}
					this._TaiKhoanKH.Entity = value;
					if ((value != null))
					{
						value.DangKyKhoaTaps.Add(this);
						this._idGuest = value.idGuest;
					}
					else
					{
						this._idGuest = default(int);
					}
					this.SendPropertyChanged("TaiKhoanKH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLB")]
	public partial class CLB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCLB;
		
		private string _CLBName;
		
		private string _addressCLB;
		
		private string _urlImage;
		
		private string _phoneNumber;
		
		private EntitySet<KhoaTap> _KhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCLBChanging(int value);
    partial void OnidCLBChanged();
    partial void OnCLBNameChanging(string value);
    partial void OnCLBNameChanged();
    partial void OnaddressCLBChanging(string value);
    partial void OnaddressCLBChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    #endregion
		
		public CLB()
		{
			this._KhoaTaps = new EntitySet<KhoaTap>(new Action<KhoaTap>(this.attach_KhoaTaps), new Action<KhoaTap>(this.detach_KhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCLB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCLB
		{
			get
			{
				return this._idCLB;
			}
			set
			{
				if ((this._idCLB != value))
				{
					this.OnidCLBChanging(value);
					this.SendPropertyChanging();
					this._idCLB = value;
					this.SendPropertyChanged("idCLB");
					this.OnidCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLBName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string CLBName
		{
			get
			{
				return this._CLBName;
			}
			set
			{
				if ((this._CLBName != value))
				{
					this.OnCLBNameChanging(value);
					this.SendPropertyChanging();
					this._CLBName = value;
					this.SendPropertyChanged("CLBName");
					this.OnCLBNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressCLB", DbType="NVarChar(128)")]
		public string addressCLB
		{
			get
			{
				return this._addressCLB;
			}
			set
			{
				if ((this._addressCLB != value))
				{
					this.OnaddressCLBChanging(value);
					this.SendPropertyChanging();
					this._addressCLB = value;
					this.SendPropertyChanged("addressCLB");
					this.OnaddressCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(128)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLB_KhoaTap", Storage="_KhoaTaps", ThisKey="idCLB", OtherKey="idCLB")]
		public EntitySet<KhoaTap> KhoaTaps
		{
			get
			{
				return this._KhoaTaps;
			}
			set
			{
				this._KhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.CLB = this;
		}
		
		private void detach_KhoaTaps(KhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.CLB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoaTap")]
	public partial class KhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCourse;
		
		private string _nameCourse;
		
		private System.Nullable<System.DateTime> _startTime;
		
		private System.Nullable<System.DateTime> _dueTime;
		
		private string _daysInWeek;
		
		private System.Nullable<int> _price;
		
		private string _descriptionKT;
		
		private string _urlImage;
		
		private System.Nullable<bool> _typeCourseName;
		
		private System.Nullable<int> _idCLB;
		
		private EntitySet<DangKyKhoaTap> _DangKyKhoaTaps;
		
		private EntityRef<CLB> _CLB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCourseChanging(int value);
    partial void OnidCourseChanged();
    partial void OnnameCourseChanging(string value);
    partial void OnnameCourseChanged();
    partial void OnstartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstartTimeChanged();
    partial void OndueTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndueTimeChanged();
    partial void OndaysInWeekChanging(string value);
    partial void OndaysInWeekChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OndescriptionKTChanging(string value);
    partial void OndescriptionKTChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    partial void OntypeCourseNameChanging(System.Nullable<bool> value);
    partial void OntypeCourseNameChanged();
    partial void OnidCLBChanging(System.Nullable<int> value);
    partial void OnidCLBChanged();
    #endregion
		
		public KhoaTap()
		{
			this._DangKyKhoaTaps = new EntitySet<DangKyKhoaTap>(new Action<DangKyKhoaTap>(this.attach_DangKyKhoaTaps), new Action<DangKyKhoaTap>(this.detach_DangKyKhoaTaps));
			this._CLB = default(EntityRef<CLB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCourse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCourse
		{
			get
			{
				return this._idCourse;
			}
			set
			{
				if ((this._idCourse != value))
				{
					this.OnidCourseChanging(value);
					this.SendPropertyChanging();
					this._idCourse = value;
					this.SendPropertyChanged("idCourse");
					this.OnidCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameCourse", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string nameCourse
		{
			get
			{
				return this._nameCourse;
			}
			set
			{
				if ((this._nameCourse != value))
				{
					this.OnnameCourseChanging(value);
					this.SendPropertyChanging();
					this._nameCourse = value;
					this.SendPropertyChanged("nameCourse");
					this.OnnameCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dueTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dueTime
		{
			get
			{
				return this._dueTime;
			}
			set
			{
				if ((this._dueTime != value))
				{
					this.OndueTimeChanging(value);
					this.SendPropertyChanging();
					this._dueTime = value;
					this.SendPropertyChanged("dueTime");
					this.OndueTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daysInWeek", DbType="NVarChar(128)")]
		public string daysInWeek
		{
			get
			{
				return this._daysInWeek;
			}
			set
			{
				if ((this._daysInWeek != value))
				{
					this.OndaysInWeekChanging(value);
					this.SendPropertyChanging();
					this._daysInWeek = value;
					this.SendPropertyChanged("daysInWeek");
					this.OndaysInWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionKT", DbType="NVarChar(1000)")]
		public string descriptionKT
		{
			get
			{
				return this._descriptionKT;
			}
			set
			{
				if ((this._descriptionKT != value))
				{
					this.OndescriptionKTChanging(value);
					this.SendPropertyChanging();
					this._descriptionKT = value;
					this.SendPropertyChanged("descriptionKT");
					this.OndescriptionKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(128)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeCourseName", DbType="Bit")]
		public System.Nullable<bool> typeCourseName
		{
			get
			{
				return this._typeCourseName;
			}
			set
			{
				if ((this._typeCourseName != value))
				{
					this.OntypeCourseNameChanging(value);
					this.SendPropertyChanging();
					this._typeCourseName = value;
					this.SendPropertyChanged("typeCourseName");
					this.OntypeCourseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCLB", DbType="Int")]
		public System.Nullable<int> idCLB
		{
			get
			{
				return this._idCLB;
			}
			set
			{
				if ((this._idCLB != value))
				{
					if (this._CLB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCLBChanging(value);
					this.SendPropertyChanging();
					this._idCLB = value;
					this.SendPropertyChanged("idCLB");
					this.OnidCLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaTap_DangKyKhoaTap", Storage="_DangKyKhoaTaps", ThisKey="idCourse", OtherKey="idCourse")]
		public EntitySet<DangKyKhoaTap> DangKyKhoaTaps
		{
			get
			{
				return this._DangKyKhoaTaps;
			}
			set
			{
				this._DangKyKhoaTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLB_KhoaTap", Storage="_CLB", ThisKey="idCLB", OtherKey="idCLB", IsForeignKey=true)]
		public CLB CLB
		{
			get
			{
				return this._CLB.Entity;
			}
			set
			{
				CLB previousValue = this._CLB.Entity;
				if (((previousValue != value) 
							|| (this._CLB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLB.Entity = null;
						previousValue.KhoaTaps.Remove(this);
					}
					this._CLB.Entity = value;
					if ((value != null))
					{
						value.KhoaTaps.Add(this);
						this._idCLB = value.idCLB;
					}
					else
					{
						this._idCLB = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.KhoaTap = this;
		}
		
		private void detach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.KhoaTap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTinTuc")]
	public partial class LoaiTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idNewType;
		
		private string _NewTypeName;
		
		private EntitySet<TinTuc> _TinTucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNewTypeChanging(int value);
    partial void OnidNewTypeChanged();
    partial void OnNewTypeNameChanging(string value);
    partial void OnNewTypeNameChanged();
    #endregion
		
		public LoaiTinTuc()
		{
			this._TinTucs = new EntitySet<TinTuc>(new Action<TinTuc>(this.attach_TinTucs), new Action<TinTuc>(this.detach_TinTucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNewType", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idNewType
		{
			get
			{
				return this._idNewType;
			}
			set
			{
				if ((this._idNewType != value))
				{
					this.OnidNewTypeChanging(value);
					this.SendPropertyChanging();
					this._idNewType = value;
					this.SendPropertyChanged("idNewType");
					this.OnidNewTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewTypeName", DbType="NVarChar(50)")]
		public string NewTypeName
		{
			get
			{
				return this._NewTypeName;
			}
			set
			{
				if ((this._NewTypeName != value))
				{
					this.OnNewTypeNameChanging(value);
					this.SendPropertyChanging();
					this._NewTypeName = value;
					this.SendPropertyChanged("NewTypeName");
					this.OnNewTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTinTuc_TinTuc", Storage="_TinTucs", ThisKey="idNewType", OtherKey="idNewType")]
		public EntitySet<TinTuc> TinTucs
		{
			get
			{
				return this._TinTucs;
			}
			set
			{
				this._TinTucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTinTuc = this;
		}
		
		private void detach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTinTuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PT")]
	public partial class PT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPT;
		
		private string _namePT;
		
		private string _phoneNumber;
		
		private string _gmail;
		
		private string _urlImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPTChanging(int value);
    partial void OnidPTChanged();
    partial void OnnamePTChanging(string value);
    partial void OnnamePTChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OngmailChanging(string value);
    partial void OngmailChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    #endregion
		
		public PT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPT
		{
			get
			{
				return this._idPT;
			}
			set
			{
				if ((this._idPT != value))
				{
					this.OnidPTChanging(value);
					this.SendPropertyChanging();
					this._idPT = value;
					this.SendPropertyChanged("idPT");
					this.OnidPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namePT", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string namePT
		{
			get
			{
				return this._namePT;
			}
			set
			{
				if ((this._namePT != value))
				{
					this.OnnamePTChanging(value);
					this.SendPropertyChanging();
					this._namePT = value;
					this.SendPropertyChanged("namePT");
					this.OnnamePTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NChar(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(100)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this.OngmailChanging(value);
					this.SendPropertyChanging();
					this._gmail = value;
					this.SendPropertyChanged("gmail");
					this.OngmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(128)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanKH")]
	public partial class TaiKhoanKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGuest;
		
		private string _passwordKH;
		
		private string _fullName;
		
		private System.Nullable<int> _phoneNumber;
		
		private System.Nullable<int> _gender;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gmail;
		
		private EntitySet<DangKyKhoaTap> _DangKyKhoaTaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGuestChanging(int value);
    partial void OnidGuestChanged();
    partial void OnpasswordKHChanging(string value);
    partial void OnpasswordKHChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnphoneNumberChanging(System.Nullable<int> value);
    partial void OnphoneNumberChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OngmailChanging(string value);
    partial void OngmailChanged();
    #endregion
		
		public TaiKhoanKH()
		{
			this._DangKyKhoaTaps = new EntitySet<DangKyKhoaTap>(new Action<DangKyKhoaTap>(this.attach_DangKyKhoaTaps), new Action<DangKyKhoaTap>(this.detach_DangKyKhoaTaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuest", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idGuest
		{
			get
			{
				return this._idGuest;
			}
			set
			{
				if ((this._idGuest != value))
				{
					this.OnidGuestChanging(value);
					this.SendPropertyChanging();
					this._idGuest = value;
					this.SendPropertyChanged("idGuest");
					this.OnidGuestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwordKH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string passwordKH
		{
			get
			{
				return this._passwordKH;
			}
			set
			{
				if ((this._passwordKH != value))
				{
					this.OnpasswordKHChanging(value);
					this.SendPropertyChanging();
					this._passwordKH = value;
					this.SendPropertyChanged("passwordKH");
					this.OnpasswordKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="Int")]
		public System.Nullable<int> phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
		public System.Nullable<int> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(50)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this.OngmailChanging(value);
					this.SendPropertyChanging();
					this._gmail = value;
					this.SendPropertyChanged("gmail");
					this.OngmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKH_DangKyKhoaTap", Storage="_DangKyKhoaTaps", ThisKey="idGuest", OtherKey="idGuest")]
		public EntitySet<DangKyKhoaTap> DangKyKhoaTaps
		{
			get
			{
				return this._DangKyKhoaTaps;
			}
			set
			{
				this._DangKyKhoaTaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKH = this;
		}
		
		private void detach_DangKyKhoaTaps(DangKyKhoaTap entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idType;
		
		private string _Title;
		
		private string _descriptionLTT;
		
		private string _content;
		
		private string _urlImage;
		
		private System.Nullable<int> _idNewType;
		
		private EntityRef<LoaiTinTuc> _LoaiTinTuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTypeChanging(int value);
    partial void OnidTypeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OndescriptionLTTChanging(string value);
    partial void OndescriptionLTTChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    partial void OnidNewTypeChanging(System.Nullable<int> value);
    partial void OnidNewTypeChanged();
    #endregion
		
		public TinTuc()
		{
			this._LoaiTinTuc = default(EntityRef<LoaiTinTuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idType", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idType
		{
			get
			{
				return this._idType;
			}
			set
			{
				if ((this._idType != value))
				{
					this.OnidTypeChanging(value);
					this.SendPropertyChanging();
					this._idType = value;
					this.SendPropertyChanged("idType");
					this.OnidTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(30)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionLTT", DbType="NVarChar(1000)")]
		public string descriptionLTT
		{
			get
			{
				return this._descriptionLTT;
			}
			set
			{
				if ((this._descriptionLTT != value))
				{
					this.OndescriptionLTTChanging(value);
					this.SendPropertyChanging();
					this._descriptionLTT = value;
					this.SendPropertyChanged("descriptionLTT");
					this.OndescriptionLTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(1000)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(128)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNewType", DbType="Int")]
		public System.Nullable<int> idNewType
		{
			get
			{
				return this._idNewType;
			}
			set
			{
				if ((this._idNewType != value))
				{
					if (this._LoaiTinTuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNewTypeChanging(value);
					this.SendPropertyChanging();
					this._idNewType = value;
					this.SendPropertyChanged("idNewType");
					this.OnidNewTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTinTuc_TinTuc", Storage="_LoaiTinTuc", ThisKey="idNewType", OtherKey="idNewType", IsForeignKey=true)]
		public LoaiTinTuc LoaiTinTuc
		{
			get
			{
				return this._LoaiTinTuc.Entity;
			}
			set
			{
				LoaiTinTuc previousValue = this._LoaiTinTuc.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTinTuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTinTuc.Entity = null;
						previousValue.TinTucs.Remove(this);
					}
					this._LoaiTinTuc.Entity = value;
					if ((value != null))
					{
						value.TinTucs.Add(this);
						this._idNewType = value.idNewType;
					}
					else
					{
						this._idNewType = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiTinTuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanQTV")]
	public partial class TaiKhoanQTV
	{
		
		private int _IDTaiKhoan;
		
		private string _MatKhau;
		
		public TaiKhoanQTV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this._IDTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
