#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_WEB_GYM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WiBuGym")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhoaTap(KhoaTap instance);
    partial void UpdateKhoaTap(KhoaTap instance);
    partial void DeleteKhoaTap(KhoaTap instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WiBuGymConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhoaTap> KhoaTaps
		{
			get
			{
				return this.GetTable<KhoaTap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoaTap")]
	public partial class KhoaTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCourse;
		
		private string _nameCourse;
		
		private System.Nullable<System.DateTime> _startTime;
		
		private System.Nullable<System.DateTime> _dueTime;
		
		private string _daysInWeek;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<int> _idTypeCourse;
		
		private string _urlImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCourseChanging(int value);
    partial void OnidCourseChanged();
    partial void OnnameCourseChanging(string value);
    partial void OnnameCourseChanged();
    partial void OnstartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstartTimeChanged();
    partial void OndueTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndueTimeChanged();
    partial void OndaysInWeekChanging(string value);
    partial void OndaysInWeekChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnidTypeCourseChanging(System.Nullable<int> value);
    partial void OnidTypeCourseChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    #endregion
		
		public KhoaTap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCourse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCourse
		{
			get
			{
				return this._idCourse;
			}
			set
			{
				if ((this._idCourse != value))
				{
					this.OnidCourseChanging(value);
					this.SendPropertyChanging();
					this._idCourse = value;
					this.SendPropertyChanged("idCourse");
					this.OnidCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameCourse", DbType="NVarChar(30)")]
		public string nameCourse
		{
			get
			{
				return this._nameCourse;
			}
			set
			{
				if ((this._nameCourse != value))
				{
					this.OnnameCourseChanging(value);
					this.SendPropertyChanging();
					this._nameCourse = value;
					this.SendPropertyChanged("nameCourse");
					this.OnnameCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dueTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dueTime
		{
			get
			{
				return this._dueTime;
			}
			set
			{
				if ((this._dueTime != value))
				{
					this.OndueTimeChanging(value);
					this.SendPropertyChanging();
					this._dueTime = value;
					this.SendPropertyChanged("dueTime");
					this.OndueTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daysInWeek", DbType="VarChar(100)")]
		public string daysInWeek
		{
			get
			{
				return this._daysInWeek;
			}
			set
			{
				if ((this._daysInWeek != value))
				{
					this.OndaysInWeekChanging(value);
					this.SendPropertyChanging();
					this._daysInWeek = value;
					this.SendPropertyChanged("daysInWeek");
					this.OndaysInWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTypeCourse", DbType="Int")]
		public System.Nullable<int> idTypeCourse
		{
			get
			{
				return this._idTypeCourse;
			}
			set
			{
				if ((this._idTypeCourse != value))
				{
					this.OnidTypeCourseChanging(value);
					this.SendPropertyChanging();
					this._idTypeCourse = value;
					this.SendPropertyChanged("idTypeCourse");
					this.OnidTypeCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="NVarChar(100)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
